### ISSUE TITLE
Get sunrise/sunset times from web services based on location

### ISSUE THREAD

**Issue by skhzhang** [skhzhang/time-based-themes#4]
Per @tlannaax on #3 :
> Moreover, it would be nice if the extension could get sunrise/sunset times from web services based on location, like what windows 10's night light schedule does.

My response:
> As for getting sunrise/sunset times based on location, that may require getting Location permissions from the user--and that's something to consider. But it would make using the addon a lot simpler. I'll also look into this as well and see if it's possible.

**Comment by sbicknel** [comment]
The Reddit Enhancement Suite extension does this.  It gets permission from the user to access the location and then sets night mode from sunset to sunrise and day mode the rest of the time.

**Comment by chrisgross** [comment]
This would be a really great feature. The default, system-color-aware Firefox theme leaves something be desired compared to the separate night and dark themes, especially because of the forced black tab bar background. If this extension could sync with sunrise and sunset, it would be a game-changer.

**Comment by skhzhang** [comment]
Included in version 1.1.0. Finished change made in e0b6927

Thanks for the resources, @sbicknel.
