### ISSUE TITLE
Extension Mozilla used at Tor Browser

### ISSUE THREAD

**Issue by GreimersStefan** [skhzhang/time-based-themes#41]
Issue: Tor Browser 12.0.3 (based on Mozilla Firefox 102.8.0esr) (64-bit), macOS 11.7.4 (20G1120) Big Sur. In the settings of automaticDark "Change themes based on the system theme" is activated. And "Do not change themes automatically (change only on startup and setup)". Now it's common for some page views to afford a white screen because the content can only be read on a white background. In your software this is impossible. Browsers like Apple Safari macOS have the app with toggle mode in the menu bar. Mozilla Firefox shows all extensions in the menu bar (?). Tor Browser doesn´t.

**Comment by skhzhang** [comment]
Hi @StefanAndPrviate ,

Are these two separate issues? For both, can you supply screenshots?

1. Now it's common for some page views to afford a white screen because the content can only be read on a white background. In your software this is impossible. 
2. Browsers like Apple Safari macOS have the app with toggle mode in the menu bar. Mozilla Firefox shows all extensions in the menu bar (?). Tor Browser doesn´t.
